-- Run this entire file in your Supabase SQL Editor

create table if not exists donors (
  id uuid default gen_random_uuid() primary key,
  formal_name text not null,
  informal_first_name text,
  email text,
  phone text,
  employer text,
  address text,
  donor_notes text,
  historical_lifetime_giving numeric(10,2) default 0,
  historical_donation_count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists donations (
  id uuid default gen_random_uuid() primary key,
  donor_id uuid references donors(id) on delete cascade,
  amount numeric(10,2) not null,
  date date not null,
  type text not null default 'one-time',
  donation_notes text,
  created_at timestamptz default now()
);

-- Index for fast donor lookups by donation date
create index if not exists donations_donor_id_idx on donations(donor_id);
create index if not exists donations_date_idx on donations(date);

-- Enable Row Level Security (open read/write for now - add auth later)
alter table donors enable row level security;
alter table donations enable row level security;

create policy "Allow all" on donors for all using (true) with check (true);
create policy "Allow all" on donations for all using (true) with check (true);

-- Donor lists / segments
create table if not exists lists (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists list_donors (
  list_id uuid references lists(id) on delete cascade,
  donor_id uuid references donors(id) on delete cascade,
  added_at timestamptz default now(),
  primary key (list_id, donor_id)
);

alter table lists enable row level security;
alter table list_donors enable row level security;

create policy "Allow all" on lists for all using (true) with check (true);
create policy "Allow all" on list_donors for all using (true) with check (true);

-- Development dashboard tasks
create table if not exists tasks (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  label text,
  status text not null default 'todo',
  due_date date,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table tasks enable row level security;
create policy "Allow all" on tasks for all using (true) with check (true);

-- GA4 analytics data (populated by Google Apps Script)
create table if not exists data_analytics (
  id uuid default gen_random_uuid() primary key,
  period text not null unique,          -- YYYY-MM
  sessions integer,
  users integer,
  page_views integer,
  bounce_rate numeric(5,4),             -- 0.0000 to 1.0000
  avg_session_duration numeric(10,2),   -- seconds
  sessions_organic integer,
  sessions_paid integer,
  sessions_direct integer,
  sessions_referral integer,
  sessions_social integer,
  sessions_email integer,
  sessions_other integer,
  created_at timestamptz default now()
);

alter table data_analytics enable row level security;
create policy "Allow all" on data_analytics for all using (true) with check (true);

-- Facebook Page analytics (populated by Google Apps Script)
create table if not exists data_facebook (
  id uuid default gen_random_uuid() primary key,
  period text not null unique,          -- YYYY-MM
  page_followers integer,
  page_impressions integer,
  page_reach integer,
  page_engaged_users integer,
  post_count integer,
  created_at timestamptz default now()
);

alter table data_facebook enable row level security;
create policy "Allow all" on data_facebook for all using (true) with check (true);

-- HoneyBook leads (synced from Google Sheet via Apps Script)
create table if not exists data_honeybook_leads (
  id uuid default gen_random_uuid() primary key,
  row_num integer,
  project_name text not null,
  full_name text not null,
  email text,
  phone text,
  project_date text,
  lead_created_date date,
  total_project_value numeric(10,2),
  lead_source text,
  lead_source_text text,
  booked_date date,
  created_at timestamptz default now()
);

alter table data_honeybook_leads enable row level security;
create policy "Allow all" on data_honeybook_leads for all using (true) with check (true);

-- Wix form submissions (synced from Apps Script)
create table if not exists data_wix_forms (
  id text primary key,
  form_id text not null,
  form_name text not null,
  status text,
  created_at timestamptz not null,
  fields jsonb not null default '{}'::jsonb,
  internal_notes text,
  synced_at timestamptz default now()
);

create index if not exists data_wix_forms_form_name_idx on data_wix_forms(form_name);
create index if not exists data_wix_forms_created_at_idx on data_wix_forms(created_at desc);

alter table data_wix_forms enable row level security;
create policy "Allow all" on data_wix_forms for all using (true) with check (true);

-- Dashboard content calendar
create table if not exists content_calendar (
  id bigint generated by default as identity primary key,
  title text not null,
  channel text not null,
  date date not null,
  notes text,
  status text not null default 'draft',
  created_at timestamptz default now()
);

create index if not exists content_calendar_date_idx on content_calendar(date);
create index if not exists content_calendar_channel_idx on content_calendar(channel);

alter table content_calendar enable row level security;
create policy "Allow all" on content_calendar for all using (true) with check (true);

create table if not exists calendar_notes (
  month text primary key,
  content text,
  updated_at timestamptz default now()
);

alter table calendar_notes enable row level security;
create policy "Allow all" on calendar_notes for all using (true) with check (true);

create table if not exists calendar_comments (
  id bigint generated by default as identity primary key,
  month text not null,
  content text not null,
  created_at timestamptz default now()
);

create index if not exists calendar_comments_month_idx on calendar_comments(month, created_at desc);

alter table calendar_comments enable row level security;
drop policy if exists "Allow all" on calendar_comments;
create policy "Allow all" on calendar_comments for all using (true) with check (true);

-- Task attachment storage bucket
insert into storage.buckets (id, name, public)
values ('task-attachments', 'task-attachments', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "Allow all task attachments read" on storage.objects;
create policy "Allow all task attachments read"
on storage.objects for select
using (bucket_id = 'task-attachments');

drop policy if exists "Allow all task attachments write" on storage.objects;
create policy "Allow all task attachments write"
on storage.objects for insert
with check (bucket_id = 'task-attachments');

drop policy if exists "Allow all task attachments update" on storage.objects;
create policy "Allow all task attachments update"
on storage.objects for update
using (bucket_id = 'task-attachments')
with check (bucket_id = 'task-attachments');

drop policy if exists "Allow all task attachments delete" on storage.objects;
create policy "Allow all task attachments delete"
on storage.objects for delete
using (bucket_id = 'task-attachments');
